
### Get CSRF Token
GET http://admin:admin@localhost:8111/authenticationTest.html?csrf

### Create project
POST http://admin:admin@localhost:8111/app/rest/projects
Accept: application/json
Content-Type: application/json
X-TC-CSRF-Token: a99a0b76-789a-4af9-969e-a76317355385

{
    "parentProject": {
        "locator": "_Root"
    },
    "name": "Test Project",
    "id": "testProjectId",
    "copyAllAssociatedSettings": true
}

### Create VCS
POST http://admin:admin@localhost:8111/app/rest/vcs-roots
Accept: application/json
Content-Type: application/json
X-TC-CSRF-Token: a9fdf64b-69c0-4542-9a1f-a92de89c8ac8

{
    "id": "MyCustomRootId",
    "name": "MyCustomRoot",
    "vcsName": "jetbrains.git",
    "project": {
        "id": "testProjectId"
    },
    "properties": {
        "property": [
            {
                "name": "authMethod",
                "value": "ANONYMOUS"
            },
            {
                "name": "branch",
                "value": "refs/heads/master"
            },
            {
                "name": "url",
                "value": "https://mygitserver.com/myrepo"
            }
        ]
    }
}

### Get Build Configuration
GET http://admin:admin@localhost:8111/app/rest/buildTypes

### Create Build Configuration
POST http://admin:admin@localhost:8111/app/rest/buildTypes
Accept: application/json
Content-Type: application/json
X-TC-CSRF-Token: a99a0b76-789a-4af9-969e-a76317355385

{
  "id": "buildId",
  "name": "testBuild",
  "project": {
    "id": "testProjectId"
  },
  "parameters": {
    "property": [
      {
        "name": "myBuildParameter",
        "value": "myValue"
      }
    ]
  },
  "steps": {
    "step": [
      {
        "name": "myCommandLineStep",
        "type": "simpleRunner",
        "properties": {
          "count": 3,
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

### Run Build Configuration
POST http://admin:admin@localhost:8111/app/rest/buildQueue
Accept: application/json
Content-Type: application/json
X-TC-CSRF-Token: a99a0b76-789a-4af9-969e-a76317355385

{
	"buildType": {
    	"id": "buildId"
	}
}

### Check Success Build Results
GET http://admin:admin@localhost:8111/app/rest/builds/id:101
Accept: application/json
Content-Type: application/json
X-TC-CSRF-Token: a99a0b76-789a-4af9-969e-a76317355385

